const projects=[
{name:'GE Healthcare – ProdGE',brand:'GE Healthcare',sub:'ProdGE',category:'Enterprise',industry:'Enterprise / Healthcare',style:'ge',overview:'Contributed to frontend/UI implementation for the ProdGE project associated with GE Healthcare, working within an enterprise development environment.',client:'General Electric Company',role:'Frontend/UI implementation'},
{name:'TMP Worldwide',brand:'TMP',sub:'Worldwide',category:'Enterprise',industry:'Enterprise / Frontend Development',style:'tmp',overview:'Converted client-supplied PSD designs into responsive HTML templates within defined delivery timelines.',client:'TMP Worldwide',role:'PSD-to-HTML implementation and client-assigned frontend tasks.',approach:'Translated visual designs into functional, responsive interfaces, with attention to cross-device layouts.',tech:['HTML5','CSS3','JavaScript','jQuery','SASS','Bootstrap','AngularJS']},
{name:'Aadhaar / UIDAI Project',brand:'Aadhaar',sub:'Government digital services',category:'Government',industry:'Government / Digital Services',style:'uidai',overview:'Contributed to UI/frontend work associated with an Aadhaar / UIDAI government project.',role:'UI/frontend implementation'},
{name:'Passport Government Project',brand:'Passport',sub:'Digital services',category:'Government',industry:'Government / Digital Services',style:'passport',overview:'Worked on frontend/UI-related activities associated with a government passport project.',role:'Frontend/UI contribution'},
{name:'Nokia Branding Project',brand:'NOKIA',sub:'Branding & UI',category:'Branding',industry:'Branding / UI',style:'nokia',overview:'Worked on frontend/UI implementation supporting Nokia branding requirements and digital brand consistency.',role:'Frontend/UI implementation',approach:'Brand consistency, design-to-code workflows and responsive presentation.'},
{name:'BrandLens Compliance Prototype',brand:'BrandLens',sub:'Brand compliance · Prototype',category:'AI',industry:'AI / Brand Compliance',style:'brandlens-ai',overview:'An interactive prototype exploring AI-assisted website validation against an organization’s branding guidelines.',role:'AI branding compliance prototype development',approach:'Explore a guided workflow for supplying brand rules, reviewing website compliance and presenting findings in a clear interface. This project is a prototype.',status:'Prototype'},
{name:'WCAG AI Validator',brand:'WCAG AI',sub:'Accessibility validator · POC',category:'AI',industry:'AI / Web Accessibility',style:'wcag-ai',overview:'An AI-assisted accessibility validation proof of concept exploring how to identify website issues and provide practical guidance for developers.',role:'AI-assisted accessibility POC development',approach:'Combine accessibility checks with clear explanations and suggested improvements. Automated findings support manual accessibility review.',status:'Proof of concept'},
{name:'CricketProAI',brand:'CricketProAI',sub:'AI-powered cricket analysis',category:'AI',industry:'AI / Sports Technology',style:'cricket-ai',overview:'An AI-powered cricket project focused on turning practice analysis into useful feedback for players and coaches.',role:'AI product development',status:'Project — implementation details available on discussion',approach:'Bring cricket analysis and player-focused feedback together in a practical digital experience.'}];
projects.sort((a,b)=>Number(b.category==='AI')-Number(a.category==='AI'));
const grid=document.querySelector('#project-grid');
function renderProjects(filter='All'){grid.innerHTML=projects.map((p,i)=>({p,i})).filter(({p})=>filter==='All'||p.category===filter).map(({p,i})=>`<article class="project"><div class="project-cover ${p.style}"><span class="cover-label">${p.category==='AI'?'AI PROJECT':p.category.toUpperCase()+' / UI'}</span><div class="project-wordmark">${p.brand}<small>${p.sub}</small></div><span class="cover-index">0${i+1}</span></div><div class="project-content"><span class="project-category">${p.industry}</span><h3>${p.name}</h3><p>${p.overview}</p><button data-project="${i}" aria-label="View details for ${p.name}">View details <span aria-hidden="true">↗</span></button></div></article>`).join('');document.querySelector('#project-count').textContent=`${grid.children.length} projects displayed`;}
renderProjects();
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});renderProjects(button.dataset.filter)}));
const dialog=document.querySelector('#project-dialog');let opener;
grid.addEventListener('click',event=>{const button=event.target.closest('[data-project]');if(!button)return;opener=button;const p=projects[Number(button.dataset.project)];document.querySelector('#dialog-body').innerHTML=`<div class="eyebrow">${p.industry}</div><h2 id="dialog-title">${p.name}</h2><h3>Project overview</h3><p>${p.overview}</p>${p.status?`<h3>Project status</h3><p>${p.status}</p>`:''}${p.client?`<h3>Client</h3><p>${p.client}</p>`:''}<h3>Role</h3><p>${p.role}</p>${p.approach?`<h3>${p.category==='AI'?'Project approach':'Frontend approach'}</h3><p>${p.approach}</p>`:''}${p.tech?`<h3>Technology</h3><div class="tags">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div>`:''}`;dialog.showModal();document.body.style.overflow='hidden'});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus()});
const skillGroups=[['Frontend development',['HTML5','CSS3','JavaScript','jQuery','SASS','Bootstrap','AngularJS']],['UI / UX implementation',['UI development','Design-to-code','UI optimization','Responsive interfaces','Cross-device compatibility']],['Accessibility',['WCAG principles','Semantic HTML','Keyboard navigation','Accessible UI']],['Performance',['Frontend optimization','Optimized assets','Responsive performance']],['SEO',['Semantic markup','SEO-friendly frontend','Technical frontend SEO']],['CMS',['WordPress','CMS development','Frontend customization']],['AI-assisted development',['ChatGPT','Cursor AI','AI-assisted coding','Development automation','Content generation','Coding and debugging support']]];

document.querySelector('#skills-grid').innerHTML=skillGroups.map(([name,skills])=>`<article class="skill-card"><h3>${name}</h3><div class="tags">${skills.map(s=>`<span>${s}</span>`).join('')}</div></article>`).join('');
const services=[['UI/UX Development','Translate visual designs into consistent, usable interfaces with clear interactions and responsive layouts.'],['Frontend Development','Build and maintain web interfaces using HTML, CSS, JavaScript and supporting frontend tools.'],['Responsive Web Development','Adapt layouts, navigation and content for mobile phones, tablets and desktop screens.'],['Website Accessibility / WCAG','Improve semantic structure, keyboard navigation, form labels and other interface details guided by WCAG principles.'],['Performance Optimization','Optimize frontend assets, styles and scripts to improve loading and rendering performance.'],['SEO-Friendly Development','Implement semantic markup, headings and page structures that support technical SEO.'],['WordPress / CMS Development','Develop and customize WordPress interfaces and CMS-powered websites.'],['AI-Assisted Development','Use ChatGPT and Cursor AI for coding assistance, debugging and repetitive development tasks.'],['Website Redesign / UI Modernization','Update existing layouts, navigation and components for better usability, responsiveness and consistency.']];
services.splice(0, services.length, ['Enterprise frontend delivery','Translate client requirements and supplied designs into responsive web interfaces.'], ['Accessibility and UI quality','Work on semantic markup, keyboard navigation, cross-browser behaviour and usable interfaces.'], ['Applied AI prototypes','Explore practical review and feedback workflows through BrandLens, WCAG AI Validator and CricketProAI.']);
function serviceMarkup(items,offset=0){return items.map(([title,copy],i)=>`<article class="service"><span>0${i+offset+1}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}
document.querySelector('#services-grid').innerHTML=serviceMarkup(services.slice(0,3));
document.querySelector('#more-services-grid').innerHTML=serviceMarkup(services.slice(3),3);
const themeButton=document.querySelector('#theme');function setTheme(theme){document.documentElement.dataset.theme=theme;themeButton.textContent=theme==='dark'?'☀':'☾';themeButton.setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} theme`);try{localStorage.setItem('sr-theme',theme)}catch{}}try{setTheme(localStorage.getItem('sr-theme')==='light'?'light':'dark')}catch{}themeButton.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const menu=document.querySelector('#menu'),nav=document.querySelector('#navigation');function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.textContent='☰'}menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus()}});
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)nav.querySelectorAll('a').forEach(a=>{const active=a.hash==='#'+entry.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})})},{rootMargin:'-20% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const data=new FormData(form),button=document.querySelector('#submit'),status=document.querySelector('#form-status');const values=Object.fromEntries(data);if(!values.name.trim()||!values.subject.trim()||!values.message.trim()){status.textContent='Please complete your name, subject and message.';return}button.disabled=true;button.textContent='Preparing…';const body=`Name: ${values.name}\nEmail: ${values.email}\nCompany: ${values.company||'—'}\n\n${values.message}`;window.location.href=`mailto:sanjayrawat452@gmail.com?subject=${encodeURIComponent(values.subject)}&body=${encodeURIComponent(body)}`;status.textContent='Your email draft is ready. Complete sending in your email app. If it did not open, use the email address alongside this form.';button.disabled=false;button.innerHTML='Prepare email <span>↗</span>';});

document.querySelector('#featured-details').addEventListener('click',()=>{
 const index=projects.findIndex(p=>p.name==='BrandLens Compliance Prototype');
 if(!document.querySelector('[data-project="'+index+'"]'))document.querySelector('[data-filter="All"]').click();
 document.querySelector('[data-project="'+index+'"]').click();opener=document.querySelector('#featured-details');
});
// Use one consistent set of line icons for global controls.
const iconSvg=(paths)=>`<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths}</svg>`;
const sunIcon=iconSvg('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>');
const moonIcon=iconSvg('<path d="M20.5 14A9 9 0 0 1 10 3.5 9 9 0 1 0 20.5 14Z"/>');
function refreshThemeIcon(){themeButton.innerHTML=document.documentElement.dataset.theme==='dark'?sunIcon:moonIcon}
refreshThemeIcon();themeButton.addEventListener('click',refreshThemeIcon);
const menuIcon=iconSvg('<path d="M4 6h16M4 12h16M4 18h16"/>'),closeIcon=iconSvg('<path d="m6 6 12 12M18 6 6 18"/>');
function refreshMenuIcon(){menu.innerHTML=menu.getAttribute('aria-expanded')==='true'?closeIcon:menuIcon}refreshMenuIcon();new MutationObserver(refreshMenuIcon).observe(menu,{attributes:true,attributeFilter:['aria-expanded']});
dialog.querySelector('.close').innerHTML=closeIcon;
